"""empty message

Revision ID: 2316c9808a5
Revises: 26fbbffb991
Create Date: 2015-04-16 13:46:41.849087

"""

# revision identifiers, used by Alembic.
revision = '2316c9808a5'
down_revision = '26fbbffb991'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('homepage', sa.Text(), nullable=True))
    op.add_column('teachers', sa.Column('avatar', sa.Integer(), nullable=True))
    op.add_column('teachers', sa.Column('homepage', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'image_store', ['avatar'], ['id'])
    op.add_column('users', sa.Column('homepage', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'homepage')
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'homepage')
    op.drop_column('teachers', 'avatar')
    op.drop_column('courses', 'homepage')
    ### end Alembic commands ###
