"""empty message

Revision ID: 26fbbffb991
Revises: None
Create Date: 2015-04-16 13:44:52.900640

"""

# revision identifiers, used by Alembic.
revision = '26fbbffb991'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_courses_dept'), 'courses', ['dept'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_index(op.f('ix_courses_term'), 'courses', ['term'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_term'), table_name='courses')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_dept'), table_name='courses')
    ### end Alembic commands ###
