"""empty message

Revision ID: 436c14e3529
Revises: 2316c9808a5
Create Date: 2015-04-16 16:09:23.391940

"""

# revision identifiers, used by Alembic.
revision = '436c14e3529'
down_revision = '2316c9808a5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('avatar_storage', table_name='users')
    op.create_foreign_key('avatar_storage', 'users', 'image_store', ['avatar_id'], ['id'])
    op.drop_column('users', 'avatar')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint('avatar_storage', 'users', type_='foreignkey')
    op.create_index('avatar_storage', 'users', ['avatar'], unique=False)
    ### end Alembic commands ###
